spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: sys123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

